#!/usr/bin/env python
"""Register backfilled evaluations and renders from the code repo into models.backfill.yaml.

    python tools/import_backfill.py [--code-repo PATH] [--dir analysis/2026-09-27_scratch/backfill]

Reads (never writes) the code repo:
    <dir>/eval/<model>_<item>.csv                          item: f20 | s2x20 | att10 | la4
    <dir>/renders/<model>_<slot>_seed<S>.mp4 + <same>_solutions.json

Copies each render into docs/assets/renders/ (skipped if an identical file is already there) and
writes models.backfill.yaml, which tools/build_model_docs.py merges into models.yaml: evaluations
only for batteries a model does not already have, renders appended. Rerun it whenever more files
land; the output is rebuilt from scratch each time.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RENDERS = ROOT / "docs" / "assets" / "renders"
ITEMS = {"f20", "s2x20", "att10", "la4"}


def md5(p: Path) -> str:
    return hashlib.md5(p.read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--code-repo", default=os.environ.get("TADA_CODE_REPO"))
    ap.add_argument("--dir", default="analysis/2026-09-27_scratch/backfill")
    args = ap.parse_args()
    reg = yaml.safe_load(open(ROOT / "models.yaml"))
    code = Path(args.code_repo or reg["code_repo"])
    base = code / args.dir
    ids = {str(m["id"]) for m in reg["models"]}
    existing = {str(m["id"]): set((m.get("evals") or {}).keys()) for m in reg["models"]}
    out: dict[str, dict] = {}
    skipped = []

    for csv in sorted((base / "eval").glob("*.csv")) if (base / "eval").exists() else []:
        mt = re.fullmatch(r"(.+)_(f20|s2x20|att10|la4)\.csv", csv.name)
        if not mt or mt.group(1) not in ids:
            skipped.append(csv.name)
            continue
        mid, item = mt.groups()
        if item in existing[mid]:
            skipped.append(f"{csv.name} (models.yaml already has {item})")
            continue
        out.setdefault(mid, {}).setdefault("evals", {})[item] = str(csv.relative_to(code))

    for mp4 in sorted((base / "renders").glob("*.mp4")) if (base / "renders").exists() else []:
        mt = re.fullmatch(r"(.+)_(comparison|best|failure)_seed(\d+)\.mp4", mp4.name)
        meta = mp4.with_name(mp4.stem + "_solutions.json")
        if not mt or mt.group(1) not in ids or not meta.exists():
            skipped.append(mp4.name + ("" if meta.exists() else " (no _solutions.json)"))
            continue
        dst = RENDERS / mp4.name
        if not dst.exists() or md5(dst) != md5(mp4):
            shutil.copy2(mp4, dst)
        out.setdefault(mt.group(1), {}).setdefault("renders", []).append(
            {"file": mp4.name, "meta": str(meta.relative_to(code))})

    header = ("# Generated by tools/import_backfill.py from the code repo's backfill directory.\n"
              "# Merged into models.yaml by tools/build_model_docs.py. Do not edit by hand; rerun the importer.\n")
    with open(ROOT / "models.backfill.yaml", "w") as f:
        f.write(header)
        yaml.safe_dump({"source": args.dir, "models": out}, f, sort_keys=True, width=200)
    n_e = sum(len(v.get("evals", {})) for v in out.values())
    n_r = sum(len(v.get("renders", [])) for v in out.values())
    print(f"registered {n_e} evaluations and {n_r} renders for {len(out)} models")
    for s in skipped:
        print("  skipped:", s)


if __name__ == "__main__":
    sys.exit(main())
